baseURL = "/"
title = "uncontained.io"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "uncontained.io"

disqusShortname = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt
enableGitInfo = true   # enable usage of git info for lastmod

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsStyle = "friendly"

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.integrations]
googleAnalyticsID = "UA-107719124-1"

[params.splash]
tagline = "On containers, cloud, and digital transformation."
text = "We are a community of experts passionate about open source emerging technologies at play in the digital transformation journey. Our aim is to provide valuable community resources to IT Organizations attempting to adopt open source and cloud technologies with an intent towards DevOps or lean methodologies."

[params.error404]
title = "Page not found"
message = "The requested page couldn't be found."
homeText = "Return to homepage"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Contribute"
weight = 1
identifier = "repository"
url = "https://github.com/redhat-cop/uncontained.io"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
